Allow redirect matching to include/exclude query string parameters when matching requests
WileyLabs/web-redirects-cli pull request #21
Opened 2022-10-31 11:15 UTC by alunwcom

Previous behaviour always added the query string to the request path before regex matching was performed. This behaviour has been revised so that by default the query string is not appended to the path - with the option to include the query string by using the new 'includeParams: {true|false}' configuration option.

In order to facilitate testing, the worker script has been converted to ES6 module format to facilitate unit testing with Miniflare and Jest. Worker unit tests have also been added.

@BigBlueHat Please review whether this is suitable for PR, or whether modification of the changes are required.

2022-10-31 14:34 UTC, BigBlueHat requested changes
Super tiny tweaks. I'm also testing this locally, atm.

2022-10-31 14:34 UTC, BigBlueHat commented on tests/lib/shared.test.js
> +    // console.log(result);
Saving this for later? 😉

2022-10-31 14:34 UTC, BigBlueHat commented on tests/worker/bar.com.yaml
> +
👻 spaces need exorcism. 😉

2022-10-31 15:17 UTC, BigBlueHat commented
@alunwcom I'm getting `SyntaxError: Cannot use import statement outside a module` which may be why this is still a Draft?

2022-10-31 15:36 UTC, BigBlueHat commented
> > @alunwcom I'm getting `SyntaxError: Cannot use import statement outside a module` which may be why this is still a Draft?
> 
> @BigBlueHat Sorry - I need to update the README here, as to run the tests you need to declare an environment variable for ES6 modules...
> 
> ```
> > $env:NODE_OPTIONS="--experimental-vm-modules npx jest"
> ```
> 
> or equivalent statement on *nix

If it's required to run the tests, you could just put it into `npm run test`. There should be a cross-platform friendly way to do the options stuff...I think you just use the all caps key/value thing without `$env`.

2022-10-31 16:29 UTC, alunwcom commented
@BigBlueHat have addressed the issues raised so far ;) ... anything else?

2022-10-31 17:34 UTC, BigBlueHat approved these changes

2022-11-01 08:47 UTC, alunwcom commented
@BigBlueHat I think you'll have to merge this - I don't appear to have access to do so....

2022-11-01 13:58 UTC, BigBlueHat commented
> @BigBlueHat I think you'll have to merge this - I don't appear to have access to do so....

You do now. 😁

2022-11-01 13:58 UTC, merged